---
meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

name: (( meta.environment "-mysql" ))
director_uuid: (( merge ))

releases:
- name: cf-mysql
  version: latest

compilation:
  workers: 3
  network: services1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: (( merge ))

resource_pools:
  - name: services-small
    network: services1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties: (( merge ))

jobs:
  - name: mysql
    release: cf-mysql
    template:
    - mysql
    instances: 1
    resource_pool: services-small
    persistent_disk: 100000
    networks:
    - name: services1
      static_ips: (( static_ips(0) ))
    properties:
      mysql:
        admin_password: changeme1
  - name: cf-mysql-broker
    release: cf-mysql
    template:
      - cf-mysql-broker
    instances: 1
    resource_pool: services-small
    networks:
    - name: services1
    properties:
      broker:
        auth_token: opensesame
      mysql_node:
        host: (( jobs.mysql.networks.services1.static_ips.[0] ))
        admin_password: (( jobs.mysql.properties.mysql.admin_password ))
